heat_template_version: 2014-10-16
 
description: >
  Install Barometer (Fastpath Quality Metrics = collectd with RDT) on compute nodes
 
# Note extra parameters can be defined, then passed data via the
# environment parameter_defaults, without modifying the parent template
parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CeilometerPassword:
    default: {}
    description: the password for the ceilometer service account
    type: string

outputs:
  role_data:
    description: Role data for Barometer role.
    value:
      service_name: barometer
      config_settings:
        barometer::collectd::public_url: {get_param: [EndpointMap, CeilometerPublic, uri]}
        barometer::collectd::ceilo_password: {get_param: CeilometerPassword}
        barometer::collectd::ceilo_username: 'ceilometer'
      step_config: |
        include ::tripleo::profile::base::barometer

