heat_template_version: newton

description: >
  OpenDaylight OVS DPDK Configuration.

parameters:
  # below parameters has to be set in neutron agent only for compute nodes.
  # as of now there is no other usecase for these parameters except dpdk.
  # should be moved to compute only ovs agent in case of any other usecases.
  NeutronDatapathType:
    default: ""
    description: Datapath type for ovs bridges
    type: string
  NeutronVhostuserSocketDir:
    default: ""
    description: The vhost-user socket directory for OVS
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  OpendaylightOvs:
    type: ./opendaylight-ovs.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the OpenDaylight DPDK service.
    value:
      service_name: opendaylight_ovs_dpdk
      config_settings:
        map_merge:
          - get_attr: [OpendaylightOvs, role_data, config_settings]
          - neutron::agents::ml2::ovs::enable_dpdk: false
            neutron::agents::ml2::ovs::datapath_type: {get_param: NeutronDatapathType}
            neutron::agents::ml2::ovs::vhostuser_socket_dir: {get_param: NeutronVhostuserSocketDir}
      step_config: {get_attr: [OpendaylightOvs, role_data, step_config]}
